'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { Brain, Sparkles, CheckCircle2, ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';

export default function CreateTestPage() {
    const router = useRouter();
    const [form, setForm] = useState({
        title: '',
        description: '',
        category: 'General Ethics',
        difficulty: 'Medium',
        questionCount: 5,
    });
    const [creating, setCreating] = useState(false);
    const [created, setCreated] = useState(false);
    const [result, setResult] = useState<any>(null);
    const [error, setError] = useState('');

    const handleCreate = async () => {
        if (!form.title.trim()) { setError('Please enter a test title'); return; }
        setCreating(true);
        setError('');

        try {
            const res = await fetch('/api/tests', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(form),
            });

            if (!res.ok) {
                const data = await res.json();
                throw new Error(data.error || 'Failed to create test');
            }

            const data = await res.json();
            setResult(data);
            setCreated(true);
        } catch (err: any) {
            setError(err.message);
        }
        setCreating(false);
    };

    if (created && result) {
        return (
            <div>
                <div className="page-header">
                    <h1>Test Created Successfully!</h1>
                </div>
                <motion.div
                    className="card"
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    style={{ maxWidth: 600, margin: '0 auto', textAlign: 'center', padding: 48 }}
                >
                    <motion.div
                        initial={{ scale: 0 }}
                        animate={{ scale: 1 }}
                        transition={{ type: 'spring', stiffness: 200 }}
                        style={{ width: 80, height: 80, borderRadius: '50%', background: 'var(--success-light)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 24px' }}
                    >
                        <CheckCircle2 size={40} style={{ color: 'var(--success)' }} />
                    </motion.div>
                    <h2 style={{ fontSize: 24, fontWeight: 800, marginBottom: 8 }}>{result.test?.title || form.title}</h2>
                    <p style={{ color: 'var(--text-secondary)', marginBottom: 24 }}>
                        {result.questionCount} questions generated by Groq AI
                    </p>
                    <div style={{ display: 'flex', justifyContent: 'center', gap: 32, marginBottom: 32 }}>
                        <div>
                            <div style={{ fontSize: 24, fontWeight: 800, color: 'var(--primary)' }}>{result.questionCount}</div>
                            <div style={{ fontSize: 12, color: 'var(--text-tertiary)' }}>Questions</div>
                        </div>
                        <div>
                            <div style={{ fontSize: 24, fontWeight: 800, color: 'var(--primary)' }}>{form.category}</div>
                            <div style={{ fontSize: 12, color: 'var(--text-tertiary)' }}>Category</div>
                        </div>
                    </div>
                    <div style={{ display: 'flex', gap: 12, justifyContent: 'center' }}>
                        <button className="btn btn-primary" onClick={() => { setCreated(false); setForm({ title: '', description: '', category: 'General Ethics', difficulty: 'Medium', questionCount: 5 }); }}>
                            Create Another
                        </button>
                        <Link href="/admin" className="btn btn-secondary">Back to Dashboard</Link>
                    </div>
                </motion.div>
            </div>
        );
    }

    return (
        <div>
            <div className="page-header">
                <Link href="/admin" style={{ fontSize: 14, color: 'var(--text-tertiary)', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}>
                    <ArrowLeft size={14} /> Back to Dashboard
                </Link>
                <h1 style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                    <Sparkles size={28} style={{ color: 'var(--primary)' }} />
                    Create AI-Powered Test
                </h1>
                <p>Generate ethics test questions using Groq AI</p>
            </div>

            <motion.div
                className="card"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                style={{ maxWidth: 640, padding: 36 }}
            >
                {error && (
                    <div style={{ padding: '12px 16px', background: '#FEF2F2', border: '1px solid #FECACA', borderRadius: 'var(--radius-sm)', color: '#DC2626', fontSize: 13, marginBottom: 20 }}>
                        {error}
                    </div>
                )}

                <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                    <div className="input-group">
                        <label>Test Title *</label>
                        <input className="input" placeholder="e.g., Q1 Knowledge Assessment 2026" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
                    </div>

                    <div className="input-group">
                        <label>Description</label>
                        <textarea className="input" rows={3} placeholder="Brief description of what this test covers..." value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} />
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                        <div className="input-group">
                            <label>Ethics Category</label>
                            <select className="input" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>
                                <option>General Ethics</option>
                                <option>Integrity</option>
                                <option>Fairness</option>
                                <option>Accountability</option>
                                <option>Transparency</option>
                                <option>Respect</option>
                            </select>
                        </div>
                        <div className="input-group">
                            <label>Difficulty</label>
                            <select className="input" value={form.difficulty} onChange={(e) => setForm({ ...form, difficulty: e.target.value })}>
                                <option>Easy</option>
                                <option>Medium</option>
                                <option>Hard</option>
                            </select>
                        </div>
                    </div>

                    <div className="input-group">
                        <label>Number of Questions</label>
                        <input className="input" type="number" min={3} max={20} value={form.questionCount} onChange={(e) => setForm({ ...form, questionCount: Number(e.target.value) })} />
                        <span style={{ fontSize: 12, color: 'var(--text-tertiary)', marginTop: 4 }}>Groq AI will generate this many scenario-based questions</span>
                    </div>

                    <button className="btn btn-primary btn-lg" style={{ width: '100%', marginTop: 8 }} onClick={handleCreate} disabled={creating || !form.title.trim()}>
                        {creating ? (
                            <><span className="loading-spinner" style={{ width: 18, height: 18, borderWidth: 2 }} /> Generating with Groq AI...</>
                        ) : (
                            <><Brain size={18} /> Generate & Publish Test</>
                        )}
                    </button>
                </div>
            </motion.div>
        </div>
    );
}
